apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{values.deployment.name}}
  labels:
    app: {{values.deployment.app}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{values.deployment.app}}
  template:
    metadata:
      labels:
        app: {{values.deployment.app}}
    spec:
      containers:
      - name: javaapp-server
        image: {{values.deployment.containers.imagename}}
        ports:
        - containerPort: 8080
