apiVersion: v1
kind: Service
metadata:
  name: {{values.service.name}}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{values.service.app}}
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodeport: 30101