apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      NodePort: 31200